apiVersion: v1
kind: Service
metadata:
  namespace: medtune
  name: caddy
spec:
  ports:
  - port: 80
    targetPort: 80
    name: "80"
  - port: 443
    targetPort: 443
    name: "443"
  selector:
    name: caddy
  type: LoadBalancer
  loadBalancerIP: "35.233.110.193"
