apiVersion: apps/v1
kind: Deployment
metadata:
  name: chief
  namespace: medtune
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chief
  template:
    metadata:
      name: chief
      labels:
        name: chief
    spec:
      containers:
      - name: chief
        image: medtune/k8s-tf:train-cod-cpu
        args: [
          "--dataset_dir", "/nfs/data/cod",
          "--train_dir", "/nfs/artefacts/cod",
          "--ckpt", "/nfs/weights/mobilenet",
        ]
        env:
          - name: TF_CONFIG
            valueFrom:
              configMapKeyRef:
                name: cod
                key: node.chief
        ports:
          - containerPort: 2222
        resources:
          requests:
            cpu: 1500m
            memory: 1000Mi
          limits:
            cpu: 5000m
            memory: 10000Mi
        volumeMounts:
          - mountPath: /nfs
            name: nfs-volume

      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: train-pvc

      restartPolicy: Always