apiVersion: apps/v1
kind: Deployment
metadata:
  name: chief
  namespace: medtune
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chief
  template:
    metadata:
      name: chief
      labels:
        name: chief
    spec:
      containers:
      - name: chief
        image: medtune/k8s-tf:train
        args: [ 
          "--train_file",  "/data/mnist/train.tfrecords",
          "--test_file", "/data/mnist/test.tfrecords",
          "--out_dir", "/artefacts",
        ]
        env:
          - name: TF_CONFIG
            valueFrom:
              configMapKeyRef:
                name: dtf-nodes-configs
                key: node.chief
        ports:
          - containerPort: 2222
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1500m
            memory: 2500Mi
        volumeMounts:
          - mountPath: /data/mnist
            name: data-volume
          - mountPath: /artefacts
            name: artefacts-volume

      volumes:
        - name: data-volume
          hostPath:
            path: /home/medtune/data
            type: Directory
        
        - name: artefacts-volume
          hostPath:
            path: /home/medtune/artefacts
            type: Directory

      restartPolicy: Always