apiVersion: batch/v1
kind: Job
metadata:
  name: inspect-volume
  namespace: medtune
spec:
  template:
    spec:
      containers:
      - name: ls-laxd
        image: ubuntu
        command: [ "ls", "-la",
          "/data/mnist" ]
        volumeMounts:
          - mountPath: /data/mnist
            name: data-volume
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
  backoffLimit: 1 # Number of retries