apiVersion: batch/v1
kind: Job
metadata:
  name: train-worker
  namespace: medtune
spec:
  selector:
    matchLabels:
      name: train-worker
  template:
    metadata:
      name: train-worker.tmpl
    spec:
      containers:
      - name: cnt-train-chief
        image: medtune/k8s-tf:train
        args: [ 
          "--train_file",  "/data/mnist/train.tfrecords",
          "--test_file", "/data/mnist/test.tfrecords",
          "--out_dir", "/data/mnist",
        ]
        env:
          - name: TF_CONFIG
            valueFrom:
              configMapKeyRef:
                name: dtf-nodes-configs
                key: node.worker
        volumeMounts:
          - mountPath: /data/mnist
            name: data-volume

      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
  backoffLimit: 1 # Number of retries