apiVersion: v1
kind: PersistentVolume
metadata:
  name: train-pv
  namespace: medtune
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /medtune_nfs/tfk8s
    server: 10.51.30.130
