apiVersion: v1
kind: PersistentVolume
metadata:
  name: train-pv
  namespace: medtune
spec:
  capacity:
    storage: 100G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /medtune_nfs/tfk8s
    server: 10.3.27.186
