apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: train-pvc
  namespace: medtune
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100G