apiVersion: batch/v1
kind: Job
metadata:
  name: inspect-volume
  namespace: medtune
spec:
  template:
    spec:
      containers:
      - name: ls-laxd
        image: alpine
        command: [ "mkdir", "-p",
          "/x/weights",
          "/x/artefacts/cod",
          "/x/artefacts/mnist",
          "/x/artefacts/mura",
          "/x/artefacts/chest",          
          "/x/data/cod",
          "/x/data/mnist",
          "/x/data/mura",
          "/x/data/chest" ]
        volumeMounts:
          - mountPath: /x
            name: nfs-volume

      restartPolicy: Never
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: train-pvc
  backoffLimit: 1 # Number of retries