apiVersion: v1
kind: ConfigMap
metadata:
  name: mura-config
  namespace: medtune
data:
  config.yaml: |
    dataset_dir: /nfs/data/mura
    train_dir: /nfs/artefacts/mura
    checkpoint_dir: /nfs/weights/mobilenet
    gpu_p: 1.
    file_pattern: mura_*.tfrecord
    file_pattern_for_counting: mura
    num_samples: 36807
    names_to_labels: {
        negative: 0,
        positive: 1,
    }
    labels_to_names : {
        "0" : negative,
        "1" : positive,
    }
    image_size: 224
    num_epochs: 100
    batch_size: 8
    initial_learning_rate: 0.0001
    learning_rate_decay_factor: 0.95
    num_epochs_before_decay: 1
    weight_decay: 0.0001
    bn_decay: 0.99
    stddev: 0.5